# Generated by Django 2.0.2 on 2018-02-19 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='no answer', max_length=100),
            preserve_default=False,
        ),
    ]
