# Generated by Django 2.0.2 on 2018-02-19 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_question_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
