# Generated by Django 2.0.2 on 2018-02-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='no ans', max_length=100),
            preserve_default=False,

        ),
    ]
